---
- name: Atualiza o cache apt-get
  apt: update_cache=yes cache_valid_time=3600

- name: Instala os pacotes necessarios
  apt: name={{ item }} state=present
  with_items:
    - mysql-server
    - php-mysql
    - python-mysqldb